import { computed } from "vue";
import { baseData } from "./base";
export const actionSheetData = computed(() => ({
  "r-action-sheet-max-height": "80%",
  "r-action-sheet-header-height": "96rpx",
  "r-action-sheet-header-font-size": baseData.value["r-font-size-lg"],
  "r-action-sheet-description-color": baseData.value["r-text-color-2"],
  "r-action-sheet-description-font-size": baseData.value["r-font-size-md"],
  "r-action-sheet-description-line-height": baseData.value["r-line-height-md"],
  "r-action-sheet-item-background": baseData.value["r-background-2"],
  "r-action-sheet-item-font-size": baseData.value["r-font-size-lg"],
  "r-action-sheet-item-line-height": baseData.value["r-line-height-lg"],
  "r-action-sheet-item-text-color": baseData.value["r-text-color"],
  "r-action-sheet-item-disabled-text-color": baseData.value["r-text-color-3"],
  "r-action-sheet-item-icon-size": "36rpx",
  "r-action-sheet-item-icon-margin-right": baseData.value["r-padding-xs"],
  "r-action-sheet-subname-color": baseData.value["r-text-color-2"],
  "r-action-sheet-subname-font-size": baseData.value["r-font-size-sm"],
  "r-action-sheet-subname-line-height": baseData.value["r-line-height-sm"],
  "r-action-sheet-close-icon-size": "44rpx",
  "r-action-sheet-close-icon-color": baseData.value["r-gray-5"],
  "r-action-sheet-close-icon-padding": `0 ${baseData.value["r-padding-md"]}`,
  "r-action-sheet-cancel-text-color": baseData.value["r-gray-7"],
  "r-action-sheet-cancel-padding-top": baseData.value["r-padding-xs"],
  "r-action-sheet-cancel-padding-color": baseData.value["r-background"],
  "r-action-sheet-loading-icon-size": "44rpx",
}));
