import { computed } from "vue";
import { baseData } from "./base";
export const uploaderData = computed(() => ({
  "r-uploader-size": "160rpx",
  "r-uploader-icon-size": "48rpx",
  "r-uploader-icon-color": baseData.value["r-gray-4"],
  "r-uploader-text-color": baseData.value["r-text-color-2"],
  "r-uploader-text-font-size": baseData.value["r-font-size-sm"],
  "r-uploader-upload-background": baseData.value["r-gray-1"],
  "r-uploader-upload-active-color": baseData.value["r-active-color"],
  "r-uploader-delete-color": baseData.value["r-white"],
  "r-uploader-delete-icon-size": "28rpx",
  "r-uploader-delete-background": "rgba(0, 0, 0, 0.7)",
  "r-uploader-file-background": baseData.value["r-background"],
  "r-uploader-file-icon-size": "40rpx",
  "r-uploader-file-icon-color": baseData.value["r-gray-7"],
  "r-uploader-file-name-padding": `0 ${baseData.value["r-padding-base"]}`,
  "r-uploader-file-name-margin-top": baseData.value["r-padding-xs"],
  "r-uploader-file-name-font-size": baseData.value["r-font-size-sm"],
  "r-uploader-file-name-text-color": baseData.value["r-background"],
  "r-uploader-mask-text-color": baseData.value["r-white"],
  "r-uploader-mask-background": "rgba(50, 50, 51, 0.88)",
  "r-uploader-mask-icon-size": "44rpx",
  "r-uploader-mask-message-font-size": baseData.value["r-font-size-sm"],
  "r-uploader-mask-message-line-height": baseData.value["r-line-height-xs"],
  "r-uploader-loading-icon-size": "44rpx",
  "r-uploader-loading-icon-color": baseData.value["r-white"],
  "r-uploader-disabled-opacity": baseData.value["r-disabled-opacity"],
  "r-uploader-border-radius": "0rpx",
}));
